env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/home/doraemon/"

task:
  name: Linux 6.0-rc1 - Xiaomi Redmi Note 10 Pro
  container:
    image: dopaemon/bionic:latest
    cpu: 4
    memory: 8G

  clone_script:
    - cd ~/
    - git clone -b v6.0-rc1 --single-branch https://github.com/dopaemon/linux.git
    - git clone -b main --single-branch https://github.com/Positron-B/android_prebuilts_gcc_linux-x86_aarch64_aarch64-none-linux-gnu.git gcc
  build_script:
    - cd ~/
    - export ARCH=arm64
    - export SUBARCH=arm64
    - export CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-none-linux-gnu-
    - cd $(pwd)/linux
    - make O=out defconfig
    - make O=out sm7150.config
    - make O=out Image.gz dtbs -j$(nproc --all)
    - make O=out bindeb-pkg -j$(nproc --all)

